language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -qq cmake valgrind g++-4.8
  - if [ "$CXX" = "g++" ]; then export CC=gcc-4.8 CXX=g++-4.8; fi
  - clang --version
  - gcc-4.8 --version

before_script:
  - git submodule update --init --recursive

script:
  - mkdir build
  - cd build
  - cmake -DLIBNODE_USE_THREAD=ON -DLIBNODE_BUILD_TEST=ON -DLIBNODE_BUILD_EXT=ON -DLIBNODE_BUILD_EXAMPLE=ON ..
  - make
  - gtest/libnode-test
  - valgrind --leak-check=full gtest/libnode-test
