language: cpp

compiler:
  - gcc

install:
  - git submodule update --init --recursive
  - sudo apt-get install cmake valgrind

before_script:
  - mkdir build
  - cd build
  - cmake -DLIBNODE_USE_THREAD=ON -DLIBNODE_BUILD_EXAMPLE=ON -DLIBNODE_BUILD_TEST=ON ..

script:
  - make

after_script:
  - gtest/libnode-test
  - valgrind --leak-check=full gtest/libnode-test
