language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -qq cmake valgrind g++-4.8
  - export CC=gcc-4.8 CXX=g++-4.8

before_script:
  - gcc-4.8 --version
  - git submodule update --init --recursive

script:
  - mkdir build
  - cd build
  - cmake -DLIBNODE_USE_THREAD=ON -DLIBNODE_BUILD_TEST=ON ..
  - make
  - gtest/libnode-test
  - valgrind --leak-check=full gtest/libnode-test
