language: cpp

compiler:
  - clang
  - gcc

before_install:
  - if [ "$CC" = "clang" ]; then export CC=clang-3.3 CXX=clang++-3.3 PKG=clang-3.3 PPA=h-rayflood/llvm; fi
  - if [ "$CC" = "gcc" ]; then export CC=gcc-4.8 CXX=g++-4.8 PKG=g++-4.8 PPA=ubuntu-toolchain-r/test; fi
  - sudo add-apt-repository -y ppa:$PPA
  - sudo apt-get -qq update
  - sudo apt-get install -qq cmake valgrind $PKG
  - $CC --version

before_script:
  - git submodule update --init --recursive

script:
  - mkdir build
  - cd build
  - cmake -DLIBNODE_USE_THREAD=ON -DLIBNODE_BUILD_TEST=ON -DLIBNODE_BUILD_EXT=ON -DLIBNODE_BUILD_EXAMPLE=ON ..
  - make
  - gtest/libnode-test
  - valgrind --leak-check=full gtest/libnode-test
